<<<<<<< Updated upstream
# Generated by Django 5.0 on 2024-04-18 13:51
=======
# Generated by Django 5.0.4 on 2024-04-19 08:26
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
=======
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('valid_upto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('father_or_husband_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=50)),
                ('is_government_servant', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(default=False)),
                ('domicile_district', models.CharField(max_length=100)),
                ('domicile_province', models.CharField(max_length=100)),
                ('postal_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('father_or_husband_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=50)),
                ('is_government_servant', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(default=False)),
                ('domicile_district', models.CharField(max_length=100)),
                ('domicile_province', models.CharField(max_length=100)),
                ('postal_address', models.TextField()),
>>>>>>> Stashed changes
            ],
        ),
    ]
