# Generated by Django 5.0.4 on 2024-04-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileView',
        ),
    ]
