# Generated by Django 5.0.4 on 2024-04-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_profileview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='License',
            new_name='License_data',
        ),
    ]
