# Generated by Django 5.0.4 on 2024-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_license_license_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='has_disability',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_government_servant',
            field=models.CharField(max_length=10),
        ),
    ]
