# Generated by Django 5.0.4 on 2024-04-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_address_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('passing_year', models.IntegerField()),
                ('marks_type', models.CharField(max_length=20)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('board_institute', models.CharField(max_length=100)),
                ('subjects', models.TextField()),
            ],
        ),
    ]
