# Generated by Django 5.0.4 on 2024-04-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_experience_alter_student_city_alter_student_name_and_more'),
        ('pages', '0007_academic_information'),
    ]

    operations = [
    ]
