# Generated by Django 5.0 on 2024-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('store_contact_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
