<<<<<<< Updated upstream
# Generated by Django 5.0 on 2024-04-18 13:51
=======
# Generated by Django 5.0.4 on 2024-04-19 01:07
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcommerceSettings',
        ),
    ]
